projectId: app-y9ytb7x5Y444PWaVUfBpcZ
appName: ordermgmt
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 5
    minReplicas: 2
    maxReplicas: 8
    dockerImage: shenalisj/cartservice
    containerPort: 8080
  OrderService:
    serviceName: orderservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: shenalisj/order
    containerPort: 8080
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 2
    minReplicas: 1
    maxReplicas: 4
    dockerImage: shenalisj/user
    containerPort: 8080
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
