apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.microservices.OrderService.serviceName}}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.microservices.OrderService.serviceName}}'
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
